apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: patient-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
