name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: dev-eks-cluster
  ECR_REPOSITORY: microservice-dev
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

     

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
