name: Deploy to Amazon EKS

on:
 workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:

env:
  CLUSTER_NAME: my-eks-cluster

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         aws-region: eu-north-1

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0     
     

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region eu-north-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infrastucture/kubernetes/appointment-deployment.yml
          kubectl apply -f infrastucture/kubernetes/appointment-service.yml
          kubectl apply -f infrastucture/kubernetes/patient-deployment.yml
          kubectl apply -f infrastucture/kubernetes/patient-service.yml

      - name: pod details
        run: |
           kubectl get pods -A
           kubectl describe pod appointment-service-64f88dc55c-grzq6  -n default
         
